name: transform_text
description: "Helps you to animate transform text when text change."
version: 1.0.1
homepage: https://github.com/RathaIct/TransformText
repository: https://github.com/RathaIct/TransformText
issue_tracker: https://github.com/RathaIct/TransformText/issues
maintainer: Hin Ratha (@RathaIct)
topics: [animate-text, animation-text, animated]
screenshots:
  - description: "TransformText thumbnail "
    path: thumbnail.png
  - description: "TransformText sample "
    path: thumbnail.gif

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
